
setupGrid2DB = {
	["profileKeys"] = {
		["Dronthal - Madmortem"] = "Dronthal - Madmortem",
	},
	["namespaces"] = {
		["Grid2Frame"] = {
			["profiles"] = {
				["Dronthal - Madmortem"] = {
					["font"] = "KkthnxUI_Normal",
					["menuDisabled"] = true,
					["frameHeights"] = {
						[30] = 35,
						[25] = 45,
						[40] = 28,
					},
					["frameTexture"] = "Grid2 Flat",
					["frameWidth"] = 74,
					["orientation"] = "HORIZONTAL",
				},
			},
		},
		["Grid2Layout"] = {
			["profiles"] = {
				["Dronthal - Madmortem"] = {
					["BackgroundG"] = 0,
					["minimapIcon"] = {
						["minimapPos"] = 200,
						["hide"] = true,
					},
					["BorderB"] = 0.5,
					["layoutBySize"] = {
						[30] = "By Group",
						[10] = "By Group",
						[20] = "By Group",
					},
					["layouts"] = {
						["raid"] = "By Group",
						["solo"] = "None",
						["party"] = "Party",
					},
					["BackgroundB"] = 0,
					["PosY"] = -538,
					["FrameLock"] = true,
					["BackgroundA"] = 0,
					["BorderR"] = 0.5,
					["Spacing"] = 4,
					["BorderTexture"] = "None",
					["BorderG"] = 0.5,
					["BackgroundR"] = 0,
					["PosX"] = 549,
				},
			},
		},
		["Grid2RaidDebuffs"] = {
			["profiles"] = {
				["Dronthal - Madmortem"] = {
					["lastSelectedModule"] = "[Custom Debuffs]",
					["enabledModules"] = {
						["Legion"] = true,
						["Cataclysm"] = true,
						["Mists of Pandaria"] = true,
						["The Burning Crusade"] = true,
						["The Lich King"] = true,
						["Warlords of Draenor"] = true,
					},
				},
			},
		},
		["Grid2AoeHeals"] = {
		},
	},
	["profiles"] = {	
		["Dronthal - Madmortem"] = {
			["hideBlizzardRaidFrames"] = true,
			["indicators"] = {
				["icon-left"] = {
					["type"] = "icon",
					["location"] = {
						["y"] = 0,
						["relPoint"] = "LEFT",
						["point"] = "LEFT",
						["x"] = 2,
					},
					["level"] = 8,
					["fontSize"] = 8,
					["size"] = 14,
				},
				["icon-center"] = {
					["type"] = "icon",
					["color1"] = {
						["a"] = 1,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
					["location"] = {
						["y"] = 0,
						["relPoint"] = "CENTER",
						["point"] = "CENTER",
						["x"] = 0,
					},
					["level"] = 8,
					["fontSize"] = 8,
					["size"] = 20,
				},
				["icon-right"] = {
					["type"] = "icon",
					["location"] = {
						["y"] = 0,
						["relPoint"] = "RIGHT",
						["point"] = "RIGHT",
						["x"] = -2,
					},
					["level"] = 8,
					["fontSize"] = 8,
					["size"] = 14,
				},
				["border"] = {
					["type"] = "border",
					["color1"] = {
						["a"] = 0,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["alpha"] = {
					["type"] = "alpha",
					["color1"] = {
						["a"] = 1,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["health-color"] = {
					["type"] = "bar-color",
				},
				["health"] = {
					["type"] = "bar",
					["location"] = {
						["y"] = 0,
						["relPoint"] = "CENTER",
						["point"] = "CENTER",
						["x"] = 0,
					},
					["level"] = 2,
					["texture"] = "Grid2 Flat",
					["color1"] = {
						["a"] = 1,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["heals-color"] = {
					["type"] = "bar-color",
				},
				["heals"] = {
					["type"] = "bar",
					["texture"] = "Grid2 Flat",
					["anchorTo"] = "health",
					["location"] = {
						["y"] = 0,
						["relPoint"] = "CENTER",
						["point"] = "CENTER",
						["x"] = 0,
					},
					["level"] = 1,
					["opacity"] = 0.25,
					["color1"] = {
						["a"] = 0,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["role"] = {
					["type"] = "icon",
					["location"] = {
						["y"] = 3,
						["relPoint"] = "CENTER",
						["point"] = "CENTER",
						["x"] = 0,
					},
					["level"] = 8,
					["fontSize"] = 8,
					["size"] = 13,
				},
				["text-up-color"] = {
					["type"] = "text-color",
				},
				["text-up"] = {
					["fontSize"] = 10,
					["type"] = "text",
					["font"] = "Friz Quadrata TT",
					["location"] = {
						["y"] = -16,
						["relPoint"] = "TOP",
						["point"] = "TOP",
						["x"] = 0,
					},
					["shadowDisabled"] = true,
					["level"] = 7,
					["textlength"] = 6,
					["fontFlags"] = "OUTLINE",
				},
				["text-down-color"] = {
					["type"] = "text-color",
				},
				["text-down"] = {
					["font"] = "Friz Quadrata TT",
					["type"] = "text",
					["fontSize"] = 10,
					["location"] = {
						["y"] = 1,
						["relPoint"] = "BOTTOM",
						["point"] = "BOTTOM",
						["x"] = 0,
					},
					["shadowDisabled"] = true,
					["level"] = 6,
					["textlength"] = 5,
					["fontFlags"] = "OUTLINE",
				},
				["bar-bottom-right-color"] = {
					["type"] = "bar-color",
				},
				["bar-bottom-left-color"] = {
					["type"] = "bar-color",
				},
				["bar-top-left-color"] = {
					["type"] = "bar-color",
				},
				["bar-top-right-color"] = {
					["type"] = "bar-color",
				},
				["bar-top-color"] = {
					["type"] = "bar-color",
				},
				["bar-bottom-color"] = {
					["type"] = "bar-color",
				},
				["bar-bottom-right"] = {
					["type"] = "bar",
					["duration"] = true,
					["width"] = 10,
					["opacity"] = 1,
					["orientation"] = "HORIZONTAL",
					["level"] = 9,
					["height"] = 5,
					["texture"] = "Grid2 Flat",
					["location"] = {
						["y"] = 2,
						["x"] = -2,
						["relPoint"] = "BOTTOMRIGHT",
						["point"] = "BOTTOMRIGHT",		
					},
				},
				["bar-bottom-left"] = {
					["type"] = "bar",
					["duration"] = true,
					["width"] = 10,
					["opacity"] = 1,
					["orientation"] = "HORIZONTAL",
					["level"] = 9,
					["height"] = 5,
					["texture"] = "Grid2 Flat",
					["location"] = {
						["y"] = 2,
						["x"] = -2,
						["relPoint"] = "BOTTOMLEFT",
						["point"] = "BOTTOMLEFT",		
					},
				},
				["bar-top-right"] = {
					["type"] = "bar",
					["duration"] = true,
					["width"] = 10,
					["opacity"] = 1,
					["orientation"] = "HORIZONTAL",
					["level"] = 9,
					["height"] = 5,
					["texture"] = "Grid2 Flat",
					["location"] = {
						["y"] = -2,
						["x"] = -2,			
						["relPoint"] = "TOPRIGHT",
						["point"] = "TOPRIGHT",
					},
				},
				["bar-top-left"] = {
					["type"] = "bar",
					["duration"] = true,
					["width"] = 10,
					["opacity"] = 1,
					["orientation"] = "HORIZONTAL",
					["level"] = 9,
					["height"] = 5,
					["texture"] = "Grid2 Flat",
					["location"] = {
						["x"] = 2,
						["y"] = -2,
						["relPoint"] = "TOPLEFT",
						["point"] = "TOPLEFT",
					},	
				},
				["bar-top"] = {
					["type"] = "bar",
					["duration"] = true,
					["width"] = 10,
					["opacity"] = 1,
					["orientation"] = "HORIZONTAL",
					["level"] = 9,
					["height"] = 5,
					["texture"] = "Grid2 Flat",
					["location"] = {
						["x"] = 0,
						["y"] = -2,
						["relPoint"] = "TOP",
						["point"] = "TOP",
					},	
				},
				["bar-bottom"] = {
					["type"] = "bar",
					["duration"] = true,
					["width"] = 10,
					["opacity"] = 1,
					["orientation"] = "HORIZONTAL",
					["level"] = 9,
					["height"] = 5,
					["texture"] = "Grid2 Flat",
					["location"] = {
						["x"] = 0,
						["y"] = 2,
						["relPoint"] = "BOTTOM",
						["point"] = "BOTTOM",
					},	
				},
				["indicator-top-left"] = {
					["type"] = "square",
					["duration"] = true,
					["color1"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["font"] = "Friz Quadrata TT",
					["borderSize"] = 1,
					["fontSize"] = 8,
					["width"] = 12,
					["height"] = 7,
					["level"] = 5,
					["textlength"] = 1,
					["location"] = {
						["y"] = -1,
						["x"] = 1,		
						["relPoint"] = "TOPLEFT",
						["point"] = "TOPLEFT",
					},	
				},
				["indicator-top-right"] = {
					["type"] = "square",
					["duration"] = true,
					["color1"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["font"] = "Friz Quadrata TT",
					["borderSize"] = 1,
					["fontSize"] = 8,
					["width"] = 12,
					["height"] = 7,
					["level"] = 5,
					["textlength"] = 1,
					["location"] = {
						["x"] = -1,
						["y"] = -1,
						["relPoint"] = "TOPRIGHT",
						["point"] = "TOPRIGHT",
					},
				},
				["indicator-bottom-right"] = {
					["type"] = "square",
					["duration"] = true,
					["color1"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["font"] = "Friz Quadrata TT",
					["borderSize"] = 1,
					["fontSize"] = 8,
					["width"] = 12,
					["height"] = 7,
					["level"] = 5,
					["textlength"] = 1,
					["location"] = {
						["x"] = -1,
						["y"] = 1,
						["relPoint"] = "BOTTOMRIGHT",
						["point"] = "BOTTOMRIGHT",
					},
				},
				["indicator-bottom-left"] = {
					["type"] = "square",
					["duration"] = true,
					["color1"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["font"] = "Friz Quadrata TT",
					["borderSize"] = 1,
					["fontSize"] = 8,
					["width"] = 12,
					["height"] = 7,
					["level"] = 5,
					["textlength"] = 1,
					["location"] = {
						["y"] = 1,
						["x"] = 1,
						["relPoint"] = "BOTTOMLEFT",
						["point"] = "BOTTOMLEFT",
					},
				},
				["indicator-top"] = {
					["type"] = "square",
					["duration"] = true,
					["color1"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["font"] = "Friz Quadrata TT",
					["borderSize"] = 1,
					["fontSize"] = 8,
					["width"] = 12,
					["height"] = 7,
					["level"] = 5,
					["textlength"] = 1,
					["location"] = {
						["x"] = 0,
						["y"] = -1,
						["relPoint"] = "TOP",
						["point"] = "TOP",
					},
				},
				["indicator-bottom"] = {
					["type"] = "square",
					["duration"] = true,
					["color1"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["font"] = "Friz Quadrata TT",
					["borderSize"] = 1,
					["fontSize"] = 8,
					["width"] = 12,
					["height"] = 7,
					["level"] = 7,
					["textlength"] = 1,
					["location"] = {
						["x"] = 0,
						["y"] = 1,
						["relPoint"] = "BOTTOM",
						["point"] = "BOTTOM",
					},
				},
			},
			["statuses"] = {
				["role"] = {
					["hideInCombat"] = true,
				},
				["color-timeroverlay"] = {
					["type"] = "color",
					["color1"] = {
						["a"] = 0.5,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["dungeon-role"] = {
					["hideDamagers"] = true,
				},
			},
			["versions"] = {
				["Grid2"] = 5,
				["Grid2RaidDebuffs"] = 1,
			},
			["statusMap"] = {
				["text-down"] = {
					["name"] = 99,
				},
				["icon-left"] = {
					["raid-icon-player"] = 155,
				},
				["border"] = {
					["banzai-threat"] = 50,
				},
				["role"] = {
					["dungeon-role"] = 51,
				},
				["icon-center"] = {
					["ready-check"] = 150,
					["raid-debuffs"] = 155,
				},
				["text-up-color"] = {
					["charmed"] = 65,
					["feign-death"] = 96,
					["health-deficit"] = 50,
					["offline"] = 93,
					["death"] = 95,
					["vehicle"] = 70,
				},
				["text-down-color"] = {
				},				
				["heals"] = {
					["heals-incoming"] = 99,
				},
				["heals-color"] = {
					["classcolor"] = 99,
				},
				["icon-right"] = {
					["raid-icon-target"] = 50,
				},
				["alpha"] = {
					["offline"] = 97,
					["range"] = 99,
					["death"] = 98,
				},
				["health-color"] = {
					["classcolor"] = 99,
				},
				["health"] = {
					["health-current"] = 99,
				},
				["text-up"] = {
					["resurrection"] = 98,
					["feign-death"] = 95,
					["death"] = 93,
					["afk"] = 97,
					["offline"] = 96,
					["vehicle"] = 70,
					["charmed"] = 65,
				},
				["bar-top-left-color"] = {
					["color-timeroverlay"] = 50,
				},
				["bar-top-right-color"] = {
					["color-timeroverlay"] = 50,
				},
				["bar-bottom-right-color"] = {
					["color-timeroverlay"] = 50,
				},	
				["bar-bottom-left-color"] = {
					["color-timeroverlay"] = 50,
				},	
				["bar-top-color"] = {
					["color-timeroverlay"] = 50,
				},
				["bar-bottom-color"] = {
					["color-timeroverlay"] = 50,
				},				
			},
		},
	},
}
